# Generated by Django 5.0.1 on 2024-01-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
